// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSBSfizD0ggChM_iMfJHE71GUF4813mWI',
    appId: '1:876439562464:web:c2b9d40b6787e8aa828885',
    messagingSenderId: '876439562464',
    projectId: 'instagram-clone-62598',
    authDomain: 'instagram-clone-62598.firebaseapp.com',
    storageBucket: 'instagram-clone-62598.appspot.com',
    measurementId: 'G-C5W1060QY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2gEPjzLS_t-bZ9AO5xSD_-cPQwY7KoNM',
    appId: '1:876439562464:android:db60f582b11a4020828885',
    messagingSenderId: '876439562464',
    projectId: 'instagram-clone-62598',
    storageBucket: 'instagram-clone-62598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNIMv46IPhGr-gfNmAESsi1v40QY-X2sY',
    appId: '1:876439562464:ios:0d9a15ff857202b9828885',
    messagingSenderId: '876439562464',
    projectId: 'instagram-clone-62598',
    storageBucket: 'instagram-clone-62598.appspot.com',
    iosBundleId: 'com.example.inistagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNIMv46IPhGr-gfNmAESsi1v40QY-X2sY',
    appId: '1:876439562464:ios:dec86833b2cde629828885',
    messagingSenderId: '876439562464',
    projectId: 'instagram-clone-62598',
    storageBucket: 'instagram-clone-62598.appspot.com',
    iosBundleId: 'com.example.inistagramClone.RunnerTests',
  );
}
